import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    zIndex: 0, 
    position: 'absolute',
  },
  lumi: {
    zIndex: 0,
    position: 'absolute',
    right: 160,
    top: 140,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    top: 250,
  },
  sloganTop: {
    color: 'white',
    fontWeight: '500',
    position: 'absolute',
    left: 100,
    top: 320,
    fontSize: 25,
    fontFamily: 'Reem-Kufi',
  },
  slogan: {
    color: 'white',
    fontWeight: '500',
    position: 'absolute',
    left: 60,
    top: 350,
    fontSize: 25,
    fontFamily: 'Reem-Kufi',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    top: 300,
    flexWrap: 'wrap',
  },
  button: {
    backgroundColor: 'purple',
    height: 50,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'Reem-Kufi',
  },
  registerButton: {
    width: 150,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '500',
    fontFamily: 'Reem-Kufi',
  },
  loginButton: {
    width: 150,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '500',
    fontFamily: 'Reem-Kufi',
  },
  formContainer: {
    marginTop: 40,
    padding: 20,
    borderRadius: 10,
    width: '90%',
    alignItems: 'center',
    marginBottom: 30,
    top: 300,
  },
  loginContainer: {
    flexDirection: 'column',
    backgroundColor: 'transparent',
    width: 300,
  },
  loginInput: {
    backgroundColor: 'transparent',
    fontSize: 25,
    width: 300,
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    marginBottom: 30,
    fontFamily: 'Reem-Kufi',
  },
  loginSubmit: {
    backgroundColor: '#FFEE92',
    padding: 20,
    borderRadius: 50,
    width: 140,
    left: 75,
    alignContent: 'center',
  },
  loginSubmitText: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '500',
    fontFamily: 'Reem-Kufi',
  },
  registerContainer: {
    flexDirection: 'column',
    backgroundColor: 'transparent',
    width: 300,
  },
  registerInput: {
    backgroundColor: 'transparent',
    fontSize: 25,
    width: 300,
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    marginBottom: 10,
    marginBottom: 30,
    fontFamily: 'Reem-Kufi',
  },
  registerSubmit: {
    backgroundColor: '#FFEE92',
    padding: 20,
    borderRadius: 50,
    width: 140,
    left: 75,
    alignContent: 'center',
  },
  registerSubmitText: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '500',
    fontFamily: 'Reem-Kufi',
  },
});

export default styles;